#!/usr/bin/env python3
"""Generate/refresh the per-task reports under reports/task-by-task/.

One report per task row in results/results.json — 30 for v1, 10 for v2. Each report is level 3
of the drill-down: level 1 is the dashboard row on `benchmark-history`, level 2 is
ui/heatmap.html, level 3 is "what did we change on this task, what worked, what didn't, and
what can we actually learn from it".

Each file is split by markers:

    <!-- BEGIN:auto ... -->   numbers, contract shape, provenance, links   <!-- END:auto -->

    ## What changed / ## What worked / ## What didn't / ## What we can (or can't) learn

Re-running rewrites ONLY the auto block of an existing file and never touches a byte outside
it. The reason for the split is that transcribed numbers drift — on the sibling
skillsbench-history branch that drift produced a heatmap that undercounted its own pass rate
and a summary.md quoting a mean that was never measured. Numbers stay derived; narrative stays
human.

Two things differ from skillsbench-history's version of this script, both because parsec's data
is shaped differently, and both deliberate:

  1. **The measurement table is vertical, not horizontal.** skillsbench could put
     seed/cand_0001/cand_0002/best in one row of columns because every cell there was measured
     at the same trial count. Parsec's are not: v1's baseline sweep is n=1 and its pilot is
     n=30; v2's `seed` is a *reused* n=3 measurement while everything else in that run is n=9.
     A horizontal row would silently invite comparing an n=3 number with an n=9 number, which
     is precisely the mistake that produced v2's headline. So every number gets its own row,
     with its `n` and its split beside it.

  2. **Narrative is pre-filled for more classes.** skillsbench pre-filled three (saturated,
     infra-failed, no-signal); here every v1 task whose story is fully determined by its own
     contract and baseline row ships written rather than as a placeholder, because for 28 of
     the 30 v1 tasks the optimizer never ran and "what happened" genuinely is the contract plus
     one trial. Placeholders are left only where a human has to read a journal to say anything
     true. `--stats` reports how many remain.

Usage:
  python3 scripts/build_task_reports.py            # create missing, refresh auto blocks
  python3 scripts/build_task_reports.py --check    # exit 1 if anything would change
  python3 scripts/build_task_reports.py --stats    # coverage report, write nothing
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS_JSON = ROOT / "results" / "results.json"
REPORTS_DIR = ROOT / "reports" / "task-by-task"

AUTO_BEGIN = "<!-- BEGIN:auto — regenerated by scripts/build_task_reports.py; do not hand-edit inside this block -->"
AUTO_END = "<!-- END:auto -->"
PLACEHOLDER = "_Not yet analysed._"

AUTO_BLOCK_RE = re.compile(re.escape(AUTO_BEGIN) + r".*?" + re.escape(AUTO_END), re.DOTALL)

# Depth from reports/task-by-task/<file>.md back to the branch root.
UP = "../.."


def fmt(v):
    return "—" if v is None else f"{v:.3f}"


def fmtd(v):
    if v is None:
        return "—"
    return f"{'+' if v >= 0 else ''}{v:.3f}"


def experiment_of(results: dict, exp: str) -> dict:
    return next(e for e in results["experiments"] if e["experiment"] == exp)


def run_of(results: dict, exp: str) -> dict:
    return next(r for r in results["runs"] if r["experiment"] == exp and r["headline"])


# --------------------------------------------------------------------------- auto block


def measurement_rows(t: dict, run: dict) -> list[tuple]:
    """(label, split, n, reward, note) — one row per distinct measurement of this task.

    Ordered oldest-instrument-first: the n=1 sweep, then whatever the pilot measured. Rows the
    run did not produce are omitted rather than shown as `—`, so the table's length is itself
    information: a 1-row table means this task was measured exactly once, ever.
    """
    rows = [(
        "baseline sweep",
        "all",
        t["baseline_n"],
        t["baseline"],
        "single trial, no optimizer — `" + run["experiment"] + "` reference sweep",
    )]
    if t["status"] != "OPTIMIZED":
        return rows

    if t.get("seed") is not None:
        note = "cap-evolve baseline on val"
        if run.get("baseline_reused"):
            note = (
                "cap-evolve baseline on val — **reused** from `"
                + run["baseline_reused"]["prior_run_dir"]
                + "`, not re-measured in this run"
            )
        rows.append(("`seed`", "val", t.get("seed_n"), t.get("seed"), note))
        if t.get("seed_all") is not None and t.get("seed_all") != t.get("seed"):
            rows.append((
                "`seed` (errored trials as 0.0)", "val", t.get("seed_n"), t.get("seed_all"),
                "same trials, other denominator",
            ))
    if t.get("seed_train") is not None:
        rows.append((
            "`seed_train`", "train", t.get("seed_train_n"), t.get("seed_train"),
            "the seed re-measured inside the iteration, at the iteration's trial count",
        ))
        if t.get("seed_train_all") is not None and t.get("seed_train_all") != t.get("seed_train"):
            rows.append((
                "`seed_train` (errored trials as 0.0)", "train", t.get("seed_train_n"),
                t.get("seed_train_all"),
                "same trials, other denominator — **this is the convention cap-evolve printed for v2**"
                if t["experiment"] == "v2" else "same trials, other denominator",
            ))
    for key, label in (("cand_0001", "`cand_0001`"), ("cand_0002", "`cand_0002`")):
        if t.get(key) is not None:
            split = "train" if t["experiment"] == "v2" else "val"
            n = t.get("seed_train_n") if t["experiment"] == "v2" else t.get("seed_n")
            verdict = "**accepted champion**" if t.get("best_tag") == key else "rejected"
            rows.append((label, split, n, t.get(key), verdict))
    if t.get("final_test") is not None:
        note = "sealed-test evaluation"
        if run.get("test_holdout") == "overlaps-train-or-val":
            note = (
                "sealed-test evaluation — **NOT held out**: this run's `test` split equals its "
                "train/val split, so read it as a fit metric"
            )
        rows.append(("`FINAL` (test)", "test", None, t.get("final_test"), note))
    return rows


def tool_list(tools: list[str]) -> str:
    """`a`, `b` and `c` — Oxford-comma-free, because these appear mid-sentence in prose."""
    q = [f"`{x}`" for x in tools]
    if len(q) == 1:
        return q[0]
    return ", ".join(q[:-1]) + " and " + q[-1]


def no_sim_exposed(tools: list[str]) -> str:
    """The clause that follows tool_list(); agrees in number."""
    return (
        "which no simulator running on 2026-08-12 exposed"
        if len(tools) == 1
        else "none of which any simulator running on 2026-08-12 exposed"
    )


def contract_line(t: dict) -> str:
    if t["experiment"] == "v1":
        n_ops = t.get("n_trajectory_ops")
        n_assn = t.get("n_assertions")
        passed = t.get("baseline_assertions_passed")
        assn = (
            "**0 assertions** — an empty list scores a vacuous `assertions: 1.0`"
            if n_assn == 0
            else f"{n_assn} `answer_contains` assertion{'s' if n_assn != 1 else ''} "
            f"(**{passed if passed is not None else '?'} passed** at baseline)"
        )
        missing = t.get("trajectory_tools_missing_at_baseline") or []
        reach = (
            "\n\n**Trajectory reachability at baseline:** the contract demands "
            + tool_list(missing)
            + f", {no_sim_exposed(missing)}. Under a "
            f"`{t.get('trajectory_match')}` match one uncallable op fails the whole containment, "
            "so `trajectory: 1.0` was **unreachable by construction** on this task and its reward "
            "was capped at 0.5 whatever the skill said."
            if missing
            else "\n\n**Trajectory reachability at baseline:** every demanded op was callable "
            "against the two simulators running on 2026-08-12. Only 5 of the 30 v1 tasks are in "
            "this position, and all 5 matched the trajectory."
        )
        return (
            f"**Contract** (`tests/expected.json`): `{t.get('trajectory_match')}` match over "
            f"**{n_ops} demanded tool call{'s' if n_ops != 1 else ''}** · {assn} · "
            "weights trajectory 0.5 / assertions 0.5 · gate requires `status == ok` and a "
            "non-empty answer." + reach
        )
    w = t.get("weights") or {}
    nd = t.get("n_derived_facts") or 0
    return (
        f"**Contract** (`tests/expected.json`, schema `bench/v2`): "
        f"**{t.get('n_expected_calls')} expected tool call{'s' if t.get('n_expected_calls') != 1 else ''}** · "
        f"**{t.get('n_required_facts')} required answer fact{'s' if t.get('n_required_facts') != 1 else ''}**"
        + (f" ({nd} *derived* — not present anywhere in the seed data)" if nd else "")
        + f" · weights tool_calls {w.get('tool_calls')} / answer {w.get('answer')}."
    )


def build_auto_block(t: dict, results: dict) -> str:
    exp = t["experiment"]
    run = run_of(results, exp)
    es = experiment_of(results, exp)

    src = "trace-extracted from a production session" if exp == "v1" else "hand-authored"
    status = t["status"]

    head = (
        f"**Status:** `{status}` · **Experiment:** `{exp}` ({src}) · "
        f"**Category:** {t['category']} / {t['subcategory']}"
    )
    if t.get("headline_run"):
        head += f" · **Run:** `{t['headline_run']}`"

    lines = [AUTO_BEGIN, "", head, ""]

    if t.get("prompt"):
        lines += ["**Prompt given to the agent:**", "", "> " + t["prompt"], ""]

    lines += [contract_line(t), ""]

    if t.get("flags"):
        lines += ["**Flags:** " + " · ".join(f"`{f}`" for f in t["flags"]), ""]

    lines += [
        "| measurement | split | n | reward | |",
        "|---|---|--:|--:|---|",
    ]
    for label, split, n, reward, note in measurement_rows(t, run):
        lines.append(
            f"| {label} | `{split}` | {n if n is not None else '—'} | **{fmt(reward)}** | {note} |"
        )
    lines.append("")

    if status == "OPTIMIZED":
        lines.append(
            f"**Best:** `{t.get('best_tag')}` @ {fmt(t.get('best'))} · "
            f"**Δ vs `seed`:** {fmtd(t.get('delta'))} · "
            f"**Iterations spent (whole run):** {t.get('iters_spent')} · "
            f"**Harness-errored trials in this task's cells:** {t.get('trials_errored')}"
        )
    else:
        lines.append(
            "**The optimizer never ran on this task.** It was not in the pilot's `val` split, "
            f"so `seed`, `best`, `delta` and `final_test` are null by construction — not zero. "
            f"Only {es['n_optimized']} of {es['n_tasks']} {exp} tasks entered cap-evolve; the "
            "other rows are a one-trial reference sweep."
        )
    lines.append("")
    lines.append(
        "_Every number above is generated from [`results/results.json`]("
        + UP + "/results/results.json). Read no cell without the `n` beside it: this branch's "
        "central finding is that the same unchanged skill measures differently at different "
        "trial counts._"
    )
    lines += ["", "**Material:**"]

    mat = []
    if exp == "v1":
        mat.append(
            f"- [`results/v1/baseline_all_1786543049.json`]({UP}/results/v1/"
            "baseline_all_1786543049.json) — the n=1 sweep row this task's baseline comes from, "
            "with its `completion` / `trajectory` / `assertions` components"
        )
        mat.append(
            f"- [`results/v1/tasks.json`]({UP}/results/v1/tasks.json) — this task's full "
            "contract: the demanded tool-call sequence and every `answer_contains` string"
        )
    else:
        mat.append(
            f"- [`results/v2/tasks.json`]({UP}/results/v2/tasks.json) — this task's full "
            "contract: expected calls, required/derived/forbidden facts, per-task weights"
        )
        mat.append(
            f"- [`results/v2/per_task_scores.csv`]({UP}/results/v2/per_task_scores.csv) — the "
            "hand-maintained per-task analysis, including a note per task per iteration. "
            "**Its numbers use the errored-as-zero denominator**, so they can differ from the "
            "table above; compare like with like"
        )
    if t.get("headline_run"):
        rd = f"{UP}/results/{exp}/runs/{t['headline_run']}"
        mat.append(f"- [`{t['headline_run']}/report.md`]({rd}/report.md) — the run's own write-up")
        if (ROOT / "results" / exp / "runs" / t["headline_run"] / "JOURNAL.md").is_file():
            mat.append(
                f"- [`{t['headline_run']}/JOURNAL.md`]({rd}/JOURNAL.md) — per-iteration "
                "hypothesis, edit, and verdict, in the optimizer's own words"
            )
        mat.append(
            f"- [`{t['headline_run']}/events.jsonl`]({rd}/events.jsonl) — the split aggregates "
            "every number above was reconciled against"
        )
    mat.append(
        f"- [`results/{exp}/per_task_scores.json`]({UP}/results/{exp}/per_task_scores.json) — "
        "per-trial reward vectors for this task in every run of this experiment, with errored "
        "trials marked `null`"
    )
    if exp == "v1":
        mat.append(
            f"- [`artifacts/v1/seed/SKILL.md`]({UP}/artifacts/v1/seed/SKILL.md) and the two "
            f"[rejected candidates]({UP}/artifacts/v1/rejected/) — diff them to see what was "
            "tried and thrown away"
        )
    else:
        mat.append(
            f"- [`artifacts/v2/best/`]({UP}/artifacts/v2/best/) vs "
            f"[`artifacts/v2/seed/`]({UP}/artifacts/v2/seed/) — the accepted champion against "
            "the seed"
        )
    mat.append(f"- [`ui/heatmap.html`]({UP}/ui/heatmap.html) — this row in context of all "
               f"{results['total_tasks']} tasks")

    lines += mat
    lines += ["", AUTO_END]
    return "\n".join(lines)


# ---------------------------------------------------------------- pre-filled narrative
#
# Only classes whose story is FULLY determined by the task's own contract plus its measured
# rows get prose here. Anything needing a journal read stays a placeholder — see --stats.


def prefill_v1(t: dict, es: dict) -> tuple[str, str, str, str, str]:
    """-> (headline, changed, worked, didnt, learn)"""
    flags = set(t.get("flags") or [])
    ops = t.get("n_trajectory_ops")
    n_assn = t.get("n_assertions")
    passed = t.get("baseline_assertions_passed")
    traj = t.get("baseline_trajectory")
    shape = es["contract_shape"]

    never_ran = (
        "**Nothing was changed on this task, because the optimizer never saw it.** The N=30 "
        f"pilot's `val` split contained {es['n_optimized']} tasks "
        "(`traces_parsec-aap2-0047` and `-0048`); this is one of the other "
        f"{es['n_baseline_only']}. It has exactly one measurement in the whole experiment: a "
        "single trial in the reference sweep."
    )
    missing = t.get("trajectory_tools_missing_at_baseline") or []
    # The load-bearing note on every unreachable task. It replaces the op-count framing an
    # earlier pass used: length is confounded (see contract_shape.op_count_confound_note),
    # coverage is not — trajectory matched on 5 of 5 reachable tasks and 0 of 25 unreachable.
    gap_note = (
        f"This task's contract demands **{ops} tool calls** in a `subset` match, including "
        + tool_list(missing)
        + f" — {no_sim_exposed(missing)}. One uncallable op fails the whole "
        "ordered containment, so **trajectory 1.0 was unreachable here by construction**, and half "
        "of this task's reward was never in play. Across v1 trajectory scored 1.0 on "
        f"{shape['trajectory_hit_when_reachable']} tasks whose demanded sequence was fully "
        f"callable and {shape['trajectory_hit_when_unreachable']} of those that were not."
        if missing
        else f"This task's contract demands **{ops} tool calls** in a `subset` match, and every "
        "one of them was callable against the simulators that were running. Only "
        f"{shape['n_tasks_trajectory_reachable_at_baseline']} of the 30 v1 tasks are in that "
        f"position, and trajectory scored 1.0 on {shape['trajectory_hit_when_reachable']} of them."
    )

    if "no-assertions-scores-vacuous-1.0" in flags:
        return (
            "the assertion list is empty — half this score measures nothing",
            never_ran,
            "N/A — nothing was attempted.",
            f"The contract is defective. `tests/expected.json` lists **zero** assertions, and an "
            f"empty list scores `assertions: 1.0` vacuously. Combined with `trajectory: 0.000` "
            f"over {ops} demanded calls, that produces a baseline of exactly **0.500** in which "
            "the agent demonstrably earned nothing: it did not reproduce the tool sequence, and "
            "there was no answer requirement for it to satisfy or miss.\n\nAnd it could not have "
            "reproduced the sequence in any case. " + gap_note,
            "**Nothing about the skill, and this row should not be in a mean.** It is the "
            "clearest single instance of the v1 benchmark's real problem: the contracts were "
            "extracted from traces mechanically and not reviewed, so a task can score 0.500 "
            "without measuring anything. Sum this task into a 30-task average and it drags the "
            f"headline **up**. It is the only such task in v1 ({', '.join(shape['tasks_with_zero_assertions'])}), "
            "which is why it is flagged on the row rather than dropped — dropping it silently "
            "would be the same class of error in the other direction.",
        )

    if "solved-at-baseline" in flags:
        return (
            "already solved on the first trial — no headroom",
            never_ran,
            f"Everything the contract asks for. The seed skill reproduced the full "
            f"{ops}-call trajectory (`trajectory: 1.000`) **and** hit all {n_assn} "
            f"`answer_contains` assertions, for a reward of exactly **1.000** — the only task in "
            "v1 to do so.",
            "Nothing failed. But note what \"solved\" means here: this is one of only "
            f"{shape['n_tasks_trajectory_reachable_at_baseline']} v1 tasks whose entire demanded "
            "sequence was callable against the simulators that were up, and trajectory matched on "
            f"{shape['trajectory_hit_when_reachable']} of those. The score is real; it is also "
            "drawn from the only part of the set where a trajectory match was possible at all.",
            "**This is a ceiling artifact, not a result.** A task already at 1.000 carries no "
            "optimizer signal — there is nothing for a candidate to improve and every direction "
            "is down. It inflates any pass-rate headline computed over all 30 tasks while "
            "contributing zero information about whether cap-evolve works. It is also a single "
            "trial: at n=1, 1.000 is not a claim that the skill solves this task reliably, only "
            "that it did once.",
        )

    if "gate-failed-at-baseline" in flags:
        # 0047 / 0048 — the two tasks the optimizer actually ran on. Deep narrative is
        # hand-written; leave placeholders rather than paraphrasing a journal badly.
        return (
            PLACEHOLDER.strip("_"),
            PLACEHOLDER, PLACEHOLDER, PLACEHOLDER, PLACEHOLDER,
        )

    if traj == 1.0:
        return (
            f"trajectory matched, {passed} of {n_assn} assertions did not",
            never_ran,
            f"The tool sequence. `trajectory: 1.000` — the seed skill reproduced all {ops} "
            "demanded calls, so it went looking in the right places in the right order.",
            f"The answer. Only **{passed} of {n_assn}** `answer_contains` assertions passed "
            f"(`assertions: {t['baseline_assertions']:.3f}`), capping the reward at "
            f"**{t['baseline']:.3f}** under the 50/50 weighting."
            + (
                " With `assertions: 0.000` against a perfect trajectory, this task scores exactly "
                "0.500 — the same as a task that got every assertion right and matched no tool "
                "calls at all. The weighting cannot tell those two apart."
                if t["baseline_assertions"] == 0.0
                else ""
            ),
            "**That the two halves of v1's reward fail independently, and that the trajectory "
            "half is the one the seed skill can already do here.** This task is in the "
            f"{shape['n_tasks_trajectory_reachable_at_baseline']}-task minority whose demanded "
            "sequence was actually callable, so it is one of the few v1 rows where trajectory is "
            "not the binding constraint — and where the score says something about the skill "
            "rather than about which simulators were running. What binds is getting specific "
            "strings into the answer, a different capability from choosing tools and the one an "
            "edit to a skill file has the best chance of moving. It was never tested: the "
            "optimizer did not run on this task.",
        )

    # trajectory == 0.0 from here.
    if "capped-at-0.5-by-50/50-weighting" in flags:
        return (
            f"every assertion passed, no trajectory credit — capped at exactly 0.500",
            never_ran,
            f"The answer. **All {n_assn} of {n_assn}** `answer_contains` assertions passed "
            "(`assertions: 1.000`) — whatever the agent did, it said the right things.",
            f"The trajectory. `trajectory: 0.000` against **{ops} demanded calls**. Because the "
            "weighting is a flat 50/50, a perfect answer with no trajectory credit scores exactly "
            "**0.500** — indistinguishable from a perfect trajectory with a worthless answer. "
            "Both appear in v1, and both read as 0.500.\n\n" + gap_note,
            "**That this 0.500 is the maximum this task could score, and that the 0.5 ceiling "
            "hides which half failed.** The trajectory term was not merely hard here, it was "
            "unearnable: a demanded op could not be called. So the agent scored everything that "
            "was available to it and the row still reads as half marks. A reader of the reward "
            "alone also cannot tell this task apart from `traces_parsec-aap2-0113`, which is its "
            "exact mirror image (trajectory 1.000, assertions 0.000) and is a genuinely different "
            "situation. The distinction only survives because the components and the tool-gap "
            "flag are carried per task in `results.json` — the aggregate destroys both.",
        )

    if "zero-at-baseline" in flags:
        return (
            "gate passed, then scored zero on both components",
            never_ran,
            "Nothing measurable. The completion gate passed — `completion: 1.000` means the "
            "agent ran to a clean stop and produced a non-empty answer — so this is not a "
            "harness failure or a crash. The agent worked and delivered something.",
            f"Both scored components. `trajectory: 0.000` over **{ops} demanded calls** and "
            f"`assertions: 0.000` over {n_assn} demanded strings: of everything the contract "
            "asked for, the agent produced none of it.\n\n" + gap_note,
            "**The assertion zero is real signal; the trajectory zero is not.** The gate passing "
            "rules out a crash — the agent ran to a clean stop and still recovered none of the "
            f"{n_assn} demanded strings, which is a genuine failure of the seed skill and makes "
            "this a good optimizer target. It was never used as one. But the other half of the "
            "0.000 is bookkeeping: the trajectory could not have been matched because a demanded "
            "op was uncallable, so only half of this row is a capability measurement. Two further "
            "caveats: n=1, and this branch's whole finding is that single measurements of this "
            "pipeline do not reproduce.",
        )

    return (
        f"partial answer credit ({passed}/{n_assn}), no trajectory credit",
        never_ran,
        f"Part of the answer. **{passed} of {n_assn}** `answer_contains` assertions passed "
        f"(`assertions: {t['baseline_assertions']:.3f}`) — the agent recovered some of the "
        "demanded facts.",
        f"The trajectory, completely. `trajectory: 0.000` against **{ops} demanded calls**. "
        f"Reward is therefore {t['baseline']:.3f} = 0.5 × 0 + 0.5 × "
        f"{t['baseline_assertions']:.3f}.\n\n" + gap_note,
        "**Where the score comes from, and how little of it is about the skill.** Half of this "
        "task's available reward sat behind a tool the harness could not call, so the `0.5 × 0` "
        "term above is a fact about the simulators, not about the skill. Only the assertion half "
        f"is a measurement, and on that half the seed skill scored {passed} of {n_assn}. The "
        f"honest ceiling for this row on 2026-08-12 was 0.500, not 1.000, which means the "
        f"reported {t['baseline']:.3f} is roughly "
        f"{t['baseline'] / 0.5:.0%} of what was actually achievable rather than "
        f"{t['baseline']:.0%}. The actionable read is that the assertion half is where movement "
        "was available — but the optimizer never ran here, so that is an inference from the "
        "contract, not a measured result.",
    )


def prefill_v2(t: dict) -> tuple[str, str, str, str, str]:
    """v2 tasks all ran through the optimizer and all have provenance worth reading.

    Nothing is pre-filled beyond the one case the data settles on its own — a task already at
    1.000 on the seed — because every other v2 story needs its `provenance.md` edit log and its
    per-iteration note, and paraphrasing those from the numbers alone would invent causes.
    """
    if (t.get("seed") or 0) >= 0.999 and (t.get("delta") or 0) <= 0:
        return (PLACEHOLDER.strip("_"), PLACEHOLDER, PLACEHOLDER, PLACEHOLDER, PLACEHOLDER)
    return (PLACEHOLDER.strip("_"), PLACEHOLDER, PLACEHOLDER, PLACEHOLDER, PLACEHOLDER)


def build_skeleton(t: dict, results: dict) -> str:
    auto = build_auto_block(t, results)
    es = experiment_of(results, t["experiment"])
    if t["experiment"] == "v1":
        headline, changed, worked, didnt, learn = prefill_v1(t, es)
    else:
        headline, changed, worked, didnt, learn = prefill_v2(t)

    title = f"# {t['task']}"
    if headline != PLACEHOLDER.strip("_"):
        title += f" — {headline}"

    # skillsbench-history printed this caution unconditionally. Here it is conditional: on 28 of
    # the 30 v1 tasks no candidate was ever evaluated, so a note about how to read a rejected
    # candidate would be filler that trains the reader to skip the italics.
    caution = ""
    if t["status"] == "OPTIMIZED" and (t.get("cand_0001") is not None):
        caution = (
            "\n_A rejected candidate is not a regression: it reverts to the champion, so a low "
            "score on a later candidate does not undo an earlier accepted fix. And a number is "
            "only comparable to another number taken at the same `n` — check the table above "
            "before reading any delta as an effect._\n"
        )

    return f"""{title}

{auto}

## What changed

{changed}

## What worked

{worked}

## What didn't

{didnt}
{caution}
## What we can (or can't) learn

{learn}
"""


# ------------------------------------------------------------------------------- main


def report_path(t: dict) -> Path:
    # results.json is the single source of truth for the filename too — build_results_json.py
    # writes the same string into the row that the heatmap links to, so a rename there
    # propagates here and to the page in one step and cannot desynchronise.
    return ROOT / t["report"]


def main() -> int:
    check_only = "--check" in sys.argv
    stats_only = "--stats" in sys.argv

    results = json.loads(RESULTS_JSON.read_text())
    tasks = results["tasks"]

    if stats_only:
        by_exp: dict = {}
        for t in tasks:
            p = report_path(t)
            e = by_exp.setdefault(t["experiment"], {"n": 0, "written": 0, "analysed": 0,
                                                    "pending": []})
            e["n"] += 1
            if p.is_file():
                e["written"] += 1
                if PLACEHOLDER in p.read_text():
                    e["pending"].append(t["task"])
                else:
                    e["analysed"] += 1
        for exp, e in sorted(by_exp.items()):
            print(f"{exp}: {e['n']} tasks · {e['written']} written · {e['analysed']} analysed "
                  f"· {len(e['pending'])} with placeholders")
            for task in e["pending"]:
                print(f"    pending: {task}")
        tot = sum(e["n"] for e in by_exp.values())
        an = sum(e["analysed"] for e in by_exp.values())
        print(f"total: {an}/{tot} fully analysed")
        orphans = sorted(
            p.name for p in (REPORTS_DIR.glob("*.md") if REPORTS_DIR.is_dir() else [])
            if p.name != "README.md" and p not in {report_path(t) for t in tasks}
        )
        if orphans:
            print("ORPHAN report files (no matching task row):")
            for o in orphans:
                print(f"    {o}")
        return 0

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    created, refreshed, unchanged, broken = [], [], [], []
    for t in tasks:
        path = report_path(t)
        if not path.is_file():
            created.append(t["task"])
            if not check_only:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(build_skeleton(t, results))
            continue

        old = path.read_text()
        if AUTO_BEGIN not in old or AUTO_END not in old:
            print(f"WARNING: {path.name} has no auto block — left untouched", file=sys.stderr)
            broken.append(t["task"])
            continue
        new = AUTO_BLOCK_RE.sub(lambda _: build_auto_block(t, results), old, count=1)
        if new == old:
            unchanged.append(t["task"])
        else:
            refreshed.append(t["task"])
            if not check_only:
                path.write_text(new)

    if check_only:
        if created or refreshed or broken:
            print(f"STALE: {len(created)} missing, {len(refreshed)} auto block(s) out of date, "
                  f"{len(broken)} unparseable.", file=sys.stderr)
            for x in created:
                print(f"  missing: {x}", file=sys.stderr)
            for x in refreshed:
                print(f"  stale:   {x}", file=sys.stderr)
            for x in broken:
                print(f"  broken:  {x}", file=sys.stderr)
            return 1
        print(f"All {len(unchanged)} task reports up to date.")
        return 0

    print(f"created {len(created)}, refreshed {len(refreshed)}, unchanged {len(unchanged)}"
          + (f", BROKEN {len(broken)}" if broken else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
