"""microcase — TDD-style micro-tests: reproduce ONE diagnosed failure deterministically,
in seconds, before any real rollout is spent on a candidate.

Adopts Harbor/Terminal-Bench's task shape (``task.yaml`` + fixture/environment + a
``tests/`` dir that asserts pass/fail and writes a reward, no LLM judge required for the
assertion itself), scoped down from "a whole task" to "the one call or turn where a
diagnosed defect lives" — see #434 section 3 and #436.

    $R/microcases/<cluster_id>/
      case.yaml       # {id, cluster_id, source_task_ids, source_rollout, timeout_s,
                       #  expects: guard_fires|call_shape|tool_selected, assert: {...}}
      fixture/          # extracted VERBATIM from the diagnosed rollout — never invented
      reproduce.py      # replays the fixture against the candidate directly: one tool
                        # call / one narrow unit, no full multi-turn episode, no LLM
      assert.py         # deterministic pass/fail against case.yaml's `assert` spec

``reproduce.py``/``assert.py`` are project-specific code (they know the candidate's tool
module) — this script cannot write them for you, only scaffold them from a real diagnosed
rollout so the author fills in the one project-aware step. What IS mechanical: extracting
the tool-call fixture verbatim, and running the case once it exists.

Two subcommands:

    python microcase.py gen  --rollout <path/to/task__tag__tK.json> \\
        --cluster-id netguard_duplicate_payment --expects guard_fires \\
        --description "..." --assert-metric payment_history_len --assert-op "<=" \\
        --assert-value 1 --out $R/microcases/netguard_duplicate_payment

    python microcase.py run  --case $R/microcases/<id> \\
        --candidate $R/work/<tag> --project P [--python PYEXE]

    python microcase.py run-all --cases-dir $R/microcases \\
        --candidate $R/work/<tag> --project P

``run``/``run-all`` never touch the run dir's budget or state — a micro-test is a
pre-rollout filter, not a rollout, and cannot itself accept a candidate (only the full-val
gate can). A ``fail`` here is the new cheap reject basis (``micro_test_fail``, see
``commit.py --reject-basis``): the mechanism the candidate claims to add provably does not
fire, discovered without spending a single evaluation.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import _bootstrap  # noqa: F401

from cap_evolve.specfile import read_yaml

VALID_EXPECTS = ("guard_fires", "call_shape", "tool_selected")
VALID_OPS = ("==", "!=", "<", "<=", ">", ">=")

CASE_TEMPLATE = """\
id: {id}
cluster_id: {cluster_id}
source_task_ids: [{source_task_ids}]
source_rollout: {source_rollout}
timeout_s: {timeout_s}
expects: {expects}
description: {description}
assert:
  metric: {assert_metric}
  op: "{assert_op}"
  value: {assert_value}
"""

REPRODUCE_STUB = '''\
#!/usr/bin/env python3
"""reproduce.py for microcase {case_id!r} — replays the fixture extracted from
{source_rollout} against the CANDIDATE's own code, directly (no LLM, no multi-turn
episode). Generated by microcase.py gen; TODO fill in the marked section — this part
is necessarily project-specific (it knows the candidate's tool module and how to
construct the minimal state the fixture's calls need).

Contract: write a JSON object to --out. On success, include whatever fields
assert.py's `assert.metric` in case.yaml needs. On an environment problem (a missing
project dependency, not a candidate defect), write {{"status": "error", "reason": ...}}
and exit 2 — that is infra, not a fail, and the runner reports it as such.
"""
import argparse
import json
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidate", required=True)
    ap.add_argument("--project", required=True)
    ap.add_argument("--fixture", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    calls = json.loads((Path(args.fixture) / "calls.json").read_text())["calls"]

    # TODO: import the candidate's tool module (Path(args.candidate) / ...), construct
    # the minimal state the fixture's calls need, replay `calls` against it in order,
    # and write the observed post-call state to args.out. Example:
    #
    #   sys.path.insert(0, str(Path(args.candidate)))
    #   from tools.tools import YourToolkitClass
    #   ...
    Path(args.out).write_text(json.dumps(
        {{"status": "error", "reason": "reproduce.py not yet implemented for this case"}}))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
'''

ASSERT_PY = '''\
#!/usr/bin/env python3
"""assert.py — deterministic pass/fail for a microcase, no LLM judge.

Reads reproduce.py's result JSON and case.yaml's `assert` spec (metric/op/value),
evaluates the comparison, and writes {status, metric, observed, expected} to --out.
Exit 0 = pass, 1 = fail, 2 = reproduce.py reported an environment error (not a fail).
"""
import argparse
import json
import operator
from pathlib import Path

OPS = {"==": operator.eq, "!=": operator.ne, "<": operator.lt,
       "<=": operator.le, ">": operator.gt, ">=": operator.ge}


def _read_case_yaml(text: str) -> dict:
    """Tiny reader for THIS script's own case.yaml shape (flat keys + one nested
    `assert:` block) — no PyYAML dependency needed for a file this script itself
    wrote via its rigid template.
    """
    try:
        import yaml  # type: ignore
        return yaml.safe_load(text) or {}
    except Exception:
        pass
    out: dict = {}
    section = None
    for raw in text.splitlines():
        if not raw.strip():
            continue
        if not raw.startswith(" "):
            key, _, val = raw.partition(":")
            key, val = key.strip(), val.strip()
            if val == "":
                section = {}
                out[key] = section
            else:
                section = None
                out[key] = json.loads(val) if val[:1] in ('[', '{', '"') or val[:1].isdigit() or val in (
                    "true", "false") else val
        elif section is not None:
            key, _, val = raw.strip().partition(":")
            key, val = key.strip(), val.strip().strip('"')
            try:
                section[key] = json.loads(val)
            except json.JSONDecodeError:
                section[key] = val
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", required=True, help="the case directory (holds case.yaml)")
    ap.add_argument("--result", required=True, help="reproduce.py's output JSON")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    case = _read_case_yaml(Path(args.case, "case.yaml").read_text())
    result = json.loads(Path(args.result).read_text())

    if result.get("status") == "error":
        out = {"status": "error", "reason": result.get("reason", "unknown")}
        Path(args.out).write_text(json.dumps(out, indent=2))
        print(json.dumps(out, indent=2))
        return 2

    spec = case["assert"]
    metric, op, expected = spec["metric"], spec["op"], spec["value"]
    if metric not in result:
        out = {"status": "error",
               "reason": f"reproduce.py's result has no {metric!r} field"}
        Path(args.out).write_text(json.dumps(out, indent=2))
        print(json.dumps(out, indent=2))
        return 2

    observed = result[metric]
    passed = OPS[op](observed, expected)
    out = {"status": "pass" if passed else "fail",
           "metric": metric, "op": op, "observed": observed, "expected": expected}
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(json.dumps(out, indent=2))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _load_rollout(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _extract_calls(rollout_record: dict) -> list[dict]:
    """Every tool call in the rollout's trace, verbatim, in order.

    Same lookup ``cluster.py``'s ``_call_names`` uses (``Rollout.tool_calls`` or an
    OpenAI-style ``tool_calls`` per message in ``Rollout.trace``) — never invented,
    never summarized.
    """
    roll = rollout_record.get("rollout", rollout_record)
    calls: list[dict] = []
    for c in roll.get("tool_calls") or []:
        calls.append({"name": c.get("name"), "arguments": c.get("arguments")})
    for msg in roll.get("trace") or []:
        if not isinstance(msg, dict):
            continue
        for c in msg.get("tool_calls") or []:
            calls.append({"name": c.get("name"), "arguments": c.get("arguments")})
    return calls


def cmd_gen(args) -> int:
    rollout_path = Path(args.rollout).resolve()
    record = _load_rollout(rollout_path)
    calls = _extract_calls(record)
    if not calls:
        print(json.dumps({
            "error": f"no tool calls found in {rollout_path}",
            "why": "a micro-case fixture is extracted from a real tool call; a rollout "
                   "with none has nothing to reproduce at this grain.",
        }, indent=2))
        return 2

    out_dir = Path(args.out).resolve()
    fixture_dir = out_dir / "fixture"
    fixture_dir.mkdir(parents=True, exist_ok=True)

    fixture_dir.joinpath("calls.json").write_text(
        json.dumps({"calls": calls}, indent=2))
    score = record.get("score")
    if score is not None:
        fixture_dir.joinpath("score.json").write_text(json.dumps(score, indent=2))

    case_id = args.cluster_id
    case_yaml = CASE_TEMPLATE.format(
        id=case_id,
        cluster_id=args.cluster_id,
        source_task_ids=", ".join(args.source_task_ids.split(",")),
        source_rollout=rollout_path.name,
        timeout_s=args.timeout_s,
        expects=args.expects,
        description=json.dumps(args.description),
        assert_metric=args.assert_metric,
        assert_op=args.assert_op,
        assert_value=json.dumps(args.assert_value),
    )
    out_dir.joinpath("case.yaml").write_text(case_yaml)

    reproduce_path = out_dir / "reproduce.py"
    if not reproduce_path.exists():
        reproduce_path.write_text(REPRODUCE_STUB.format(
            case_id=case_id, source_rollout=rollout_path.name))
    assert_path = out_dir / "assert.py"
    if not assert_path.exists():
        assert_path.write_text(ASSERT_PY)

    result = {
        "case_dir": str(out_dir),
        "calls_extracted": len(calls),
        "wrote": [str(out_dir / "case.yaml"), str(fixture_dir / "calls.json"),
                  str(reproduce_path), str(assert_path)],
        "next_step": f"fill in the TODO in {reproduce_path} — the rest runs as-is",
    }
    print(json.dumps(result, indent=2))
    return 0


def _run_one(case_dir: Path, candidate: Path, project: Path, python: str) -> dict:
    case = read_yaml((case_dir / "case.yaml").read_text(encoding="utf-8"))
    timeout_s = float(case.get("timeout_s", 10))
    t0 = time.time()
    # Scratch files, NOT written beside case.yaml: a case directory is often a
    # committed fixture (this run's own worked example included), and running it
    # must not dirty that tree with per-run output.
    scratch = Path(tempfile.mkdtemp(prefix="microcase_"))
    result_path = scratch / "result.json"
    verdict_path = scratch / "verdict.json"

    try:
        return _run_one_in(case_dir, candidate, project, python, case, timeout_s, t0,
                           result_path, verdict_path)
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


def _run_one_in(case_dir, candidate, project, python, case, timeout_s, t0,
                result_path, verdict_path) -> dict:
    try:
        proc = subprocess.run(
            [python, str(case_dir / "reproduce.py"),
             "--candidate", str(candidate), "--project", str(project),
             "--fixture", str(case_dir / "fixture"), "--out", str(result_path)],
            capture_output=True, text=True, timeout=timeout_s,
        )
    except subprocess.TimeoutExpired:
        return {"case_id": case.get("id", case_dir.name), "status": "error",
                "reason": f"reproduce.py exceeded timeout_s={timeout_s}",
                "wall_seconds": round(time.time() - t0, 3)}

    if proc.returncode not in (0, 2) or not result_path.exists():
        return {"case_id": case.get("id", case_dir.name), "status": "error",
                "reason": f"reproduce.py exit {proc.returncode}: "
                          f"{(proc.stderr or proc.stdout)[-2000:]}",
                "wall_seconds": round(time.time() - t0, 3)}

    if proc.returncode == 2:
        verdict = json.loads(result_path.read_text())
        verdict.setdefault("status", "error")
    else:
        assert_proc = subprocess.run(
            [python, str(case_dir / "assert.py"), "--case", str(case_dir),
             "--result", str(result_path), "--out", str(verdict_path)],
            capture_output=True, text=True, timeout=timeout_s,
        )
        if not verdict_path.exists():
            return {"case_id": case.get("id", case_dir.name), "status": "error",
                    "reason": f"assert.py exit {assert_proc.returncode}: "
                              f"{(assert_proc.stderr or assert_proc.stdout)[-2000:]}",
                    "wall_seconds": round(time.time() - t0, 3)}
        verdict = json.loads(verdict_path.read_text())

    verdict["case_id"] = case.get("id", case_dir.name)
    verdict["wall_seconds"] = round(time.time() - t0, 3)
    return verdict


def cmd_run(args) -> int:
    verdict = _run_one(Path(args.case).resolve(), Path(args.candidate).resolve(),
                        Path(args.project).resolve(), args.python)
    print(json.dumps(verdict, indent=2))
    return {"pass": 0, "fail": 1}.get(verdict.get("status"), 2)


def cmd_run_all(args) -> int:
    cases_dir = Path(args.cases_dir).resolve()
    cand = Path(args.candidate).resolve()
    proj = Path(args.project).resolve()
    verdicts = []
    for case_dir in sorted(p for p in cases_dir.iterdir()
                           if p.is_dir() and (p / "case.yaml").exists()):
        verdicts.append(_run_one(case_dir, cand, proj, args.python))
    failed = [v for v in verdicts if v.get("status") == "fail"]
    errored = [v for v in verdicts if v.get("status") == "error"]
    out = {
        "candidate": str(cand),
        "cases": len(verdicts),
        "failed": [v["case_id"] for v in failed],
        "errored": [v["case_id"] for v in errored],
        "verdicts": verdicts,
        "micro_test_fail": bool(failed),
        "recommendation": (
            "reject --reject-basis micro_test_fail: the mechanism this candidate "
            "targets provably does not fire — no rollout needed" if failed else
            "proceed to screen/full-val" if not errored else
            "cases errored (infra, not a candidate defect) — fix the case or its "
            "environment before trusting a pass here"
        ),
    }
    print(json.dumps(out, indent=2))
    return 1 if failed else 0


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="microcase")
    sub = p.add_subparsers(dest="cmd", required=True)

    g = sub.add_parser("gen", help="scaffold a case from a real diagnosed rollout")
    g.add_argument("--rollout", required=True,
                   help="path to the rollout record (<task>__<tag>__t<k>.json)")
    g.add_argument("--cluster-id", required=True,
                   help="filename-safe id — also the case's own id, by convention")
    g.add_argument("--source-task-ids", required=True, help="comma-separated task ids")
    g.add_argument("--expects", required=True, choices=VALID_EXPECTS)
    g.add_argument("--description", required=True)
    g.add_argument("--assert-metric", required=True,
                   help="key in reproduce.py's result JSON that assert.py compares")
    g.add_argument("--assert-op", required=True, choices=VALID_OPS)
    g.add_argument("--assert-value", required=True,
                   help="JSON-decoded if it parses (so 1, true, \"x\" all work); else kept as a string")
    g.add_argument("--timeout-s", type=float, default=10.0)
    g.add_argument("--out", required=True, help="the case directory to write")
    g.set_defaults(func=cmd_gen)

    r = sub.add_parser("run", help="run ONE case against a candidate")
    r.add_argument("--case", required=True)
    r.add_argument("--candidate", required=True)
    r.add_argument("--project", required=True)
    r.add_argument("--python", default=sys.executable)
    r.set_defaults(func=cmd_run)

    ra = sub.add_parser("run-all", help="run every case under a directory against a candidate")
    ra.add_argument("--cases-dir", required=True)
    ra.add_argument("--candidate", required=True)
    ra.add_argument("--project", required=True)
    ra.add_argument("--python", default=sys.executable)
    ra.set_defaults(func=cmd_run_all)

    args = p.parse_args(argv)
    if args.cmd == "gen":
        try:
            args.assert_value = json.loads(args.assert_value)
        except json.JSONDecodeError:
            pass
        args.timeout_s = int(args.timeout_s) if float(args.timeout_s).is_integer() else args.timeout_s
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
